### ISSUE TITLE
Not working on Safari 6.0.5

### ISSUE THREAD

**Issue by eshiota** [eshiota/retro-audio-js#6]
`TypeError: 'undefined' is not a function (evaluating 'i.start(0)') on Oscillator.js:4`
